// GENERATED by scripts/gen-capabilities.cjs. Do not edit by hand.
// Source: core/capabilities/protocols.json.

export const inboundTypes = ["socks", "http", "mixed", "shadowsocks", "vmess", "vless", "trojan", "naive", "hysteria", "hysteria2", "tuic", "anytls", "shadowtls", "direct", "tun", "redirect", "tproxy"] as const
export const inboundWithUsers = ["socks", "http", "mixed", "shadowsocks", "vmess", "vless", "trojan", "naive", "hysteria", "hysteria2", "tuic", "anytls", "shadowtls"] as const
export const HasInData = ["socks", "http", "mixed", "shadowsocks", "vmess", "vless", "trojan", "naive", "hysteria", "hysteria2", "tuic", "anytls", "shadowtls"] as const
export const HasTls = ["http", "vmess", "vless", "trojan", "naive", "hysteria", "hysteria2", "tuic", "anytls"] as const
export const MuxAvailable = ["shadowsocks", "vmess", "vless", "trojan"] as const
export const OnlyTLS = ["naive", "hysteria", "hysteria2", "tuic", "anytls"] as const
export const inboundEditors = {
  "socks": "Socks",
  "http": "Http",
  "mixed": "Mixed",
  "shadowsocks": "Shadowsocks",
  "vmess": "VMess",
  "vless": "Vless",
  "trojan": "Trojan",
  "naive": "Naive",
  "hysteria": "Hysteria",
  "hysteria2": "Hysteria2",
  "tuic": "Tuic",
  "anytls": "AnyTls",
  "shadowtls": "ShadowTls",
  "direct": "Direct",
  "tun": "Tun",
  "redirect": "Redirect",
  "tproxy": "TProxy"
} as const
export const outboundCapabilities = [
  {
    "type": "direct",
    "buildTag": ""
  },
  {
    "type": "block",
    "buildTag": ""
  },
  {
    "type": "socks",
    "buildTag": ""
  },
  {
    "type": "http",
    "buildTag": ""
  },
  {
    "type": "shadowsocks",
    "buildTag": ""
  },
  {
    "type": "vmess",
    "buildTag": ""
  },
  {
    "type": "vless",
    "buildTag": ""
  },
  {
    "type": "trojan",
    "buildTag": ""
  },
  {
    "type": "naive",
    "buildTag": "with_naive_outbound"
  },
  {
    "type": "tor",
    "buildTag": ""
  },
  {
    "type": "ssh",
    "buildTag": ""
  },
  {
    "type": "shadowtls",
    "buildTag": ""
  },
  {
    "type": "anytls",
    "buildTag": ""
  },
  {
    "type": "hysteria",
    "buildTag": "with_quic"
  },
  {
    "type": "hysteria2",
    "buildTag": "with_quic"
  },
  {
    "type": "tuic",
    "buildTag": "with_quic"
  }
] as const
export const endpointCapabilities = [
  {
    "type": "wireguard",
    "buildTag": "with_wireguard"
  },
  {
    "type": "tailscale",
    "buildTag": "with_tailscale"
  }
] as const
export const serviceCapabilities = [
  {
    "type": "resolved",
    "buildTag": ""
  },
  {
    "type": "ssm-api",
    "buildTag": ""
  },
  {
    "type": "derp",
    "buildTag": "with_tailscale"
  }
] as const
export const outboundGroupCapabilities = [
  {
    "type": "selector",
    "coreType": "selector",
    "sessionRecovery": false,
    "notes": "Manual operator-selected group backed directly by the core selector outbound."
  },
  {
    "type": "urltest",
    "coreType": "urltest",
    "sessionRecovery": false,
    "notes": "Latency-based group backed directly by the core urltest outbound."
  },
  {
    "type": "failover",
    "assembledAs": "selector",
    "panelManaged": true,
    "sessionRecovery": false,
    "notes": "Panel-managed priority failover assembled as a core selector."
  }
] as const
